server:
  port: 8081
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

yeguo:
  api:
    access-key: ak12315
    secret-key: sk212312jsp

