spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/api?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ""
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0

server:
  servlet:
    session:
      timeout: 300m       # 5 hours
      cookie:
        path: /api
        max-age: 18000    # 5 hours
        secure: true
        http-only: true
        same-site: lax